import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { ConnectButton } from '@rainbow-me/rainbowkit'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="flex flex-col items-center justify-between p-24">
            <ConnectButton />
          </main>
          {children}
        </Providers>
      </body>
    </html >
  )
}
